apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.webhooks.mutatingWebhook.name }}
  namespace: {{ .Release.Namespace }}
webhooks:
  - name: microenforcer.aquasec.com
    sideEffects: "None"
    failurePolicy: {{ .Values.webhooks.failurePolicy }}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods"]
    clientConfig:
      {{- if not .Values.webhooks.certManager }}
      caBundle: {{ template "caBundle" . }}
      {{- end }}
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "kube-enforcer.fullname" . }}
        path: "/mutate"
    timeoutSeconds: 5
    failurePolicy: Ignore
    admissionReviewVersions: ["v1beta1"]
    sideEffects: "None"
