apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.webhooks.validatingWebhook.name }}
  namespace: {{ .Release.Namespace }}
webhooks:
  - name: imageassurance.aquasec.com
    failurePolicy: {{ .Values.webhooks.failurePolicy }}
    sideEffects: "None"
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources:
          - pods
          - deployments
          - replicasets
          - replicationcontrollers
          - statefulsets
          - daemonsets
          - jobs
          - cronjobs
          - configmaps
          - services
          - roles
          - rolebindings
          - clusterroles
          - clusterrolebindings
          - customresourcedefinitions
    clientConfig:
      {{- if not .Values.webhooks.certManager }}
      caBundle: {{ template "caBundle" . }}
      {{- end }}
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "kube-enforcer.fullname" . }}
    timeoutSeconds: 5
    failurePolicy: Ignore
    admissionReviewVersions: ["v1beta1"]
    sideEffects: "None"
